include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    depend_on_referenced_packages: ignore
    no_leading_underscores_for_local_identifiers: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_void_async: true
    directives_ordering: true
    prefer_final_fields: false
    unawaited_futures: true
