include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_final_locals: ignore
    unnecessary_new: ignore
    unused_import: warning
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    depend_on_referenced_packages: ignore
    sort_child_properties_last: ignore
    unnecessary_string_interpolations: ignore
    
linter:
  rules:
    use_key_in_widget_constructors: false
    prefer_const_constructors: false
    prefer_final_fields: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_types_as_parameter_names: false
    sized_box_for_whitespace: false
    no_leading_underscores_for_local_identifiers: false
