workflows:
  ios-release-build:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: 3.24.5
      xcode: 15.4
      cocoapods: 1.16.2
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Pod Setup
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=ios/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      provisioning_profiles:
        com.aifun.dateideas.planadate: "SoulPlan_ProvisioningProfile.mobileprovision"
      certificate: "SoulPlan_Certificate.p12"
      certificate_password: xclavisanaspasse14
   publishing:
  app_store_connect:
    apple_id: anaskay.13@gmail.com
    api_key_id: QDVWVZNYHW
    api_key_issuer_id: 1286bc9f-7590-4626-a04a-9acdd2431c04
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    bundle_identifier: "com.aifun.dateideas.planadate"
