workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Pod Setup
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
        auth: integration
