workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Pod Setup
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
        key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_identifier: $APP_STORE_API_KEY_ID
        issuer_id: $APP_STORE_API_KEY_ISSUER_ID
