name: soulplan_ai_fun_date_ideas
description: "AI Date Planner with Emotional Insight Concept"
publish_to: 'none'
version: 16.0.0+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.2
  app_tracking_transparency: ^2.0.6
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  cloud_firestore: ^4.8.2
  collection: 1.18.0
  connectivity_plus: ^6.1.0
  country_flags: ^2.2.0
  country_icons: ^2.0.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  equatable: ^2.0.5
  facebook_audience_network: ^1.0.1
  firebase_app_check: 0.1.4+3
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  firebase_crashlytics: 3.3.3
  firebase_storage: 11.2.3
  flag: ^7.0.0
  flutter_animate: ^4.5.0
  flutter_animated_button: ^2.0.3
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.3.0
  flutter_image_slideshow: ^0.1.6
  flutter_markdown: ^0.7.4+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.1.6
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^3.1.3
  nb_utils: ^7.0.6
  octo_image: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.10.7
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  printing: ^5.11.1
  profanity_filter: ^2.0.0
  provider: ^6.1.2
  retry: ^3.1.2
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  simple_animations: ^5.0.2
  timeago: ^3.5.0
  translator: ^1.0.3+1
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.0
  win32: ^5.7.2
  webview_flutter_wkwebview: ^3.16.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - images/
    - assets/icons/
    - assets/animations/
    - assets/images/
    - animations/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Bold.ttf
          weight: 700

